### ISSUE TITLE
How-to?

### ISSUE THREAD

**Issue by sandmen** [julianZeitler/cat-flap#7]
Hi, 
is there any "how-to" planned, how to try out this project ?
Thanks

**Comment by julianZeitler** [comment]
Hello,
Yes I can do that. I have to clean up the code some more. You would probably have to collect data for your own cat because the models are specifically trained on my cat.
If you're interested, you could also provide me with the data you collected and I can then train the ml model on more data to make it more robust.

**Comment by sandmen** [comment]
Ok, what kind of data format is preferred?
I imaging, it makes sense to install raspi cam Close to the flap, and record some pictures if the cat is available.

**Comment by julianZeitler** [comment]
Yes that's exactly what I did. The camera is installed right next to the flap and records a video, as soon as it detects a motion. This video is then split into individual frames which will be used for training. I implemented it that way to make the data collection more efficient because you get multiple images if the cat enters. All the functions for that are already available in the repo, so the pictures will already have the correct format. I will start to write the how-to today.

**Comment by julianZeitler** [comment]
The hardware list is outdated. I didn't use any sensor in the final implementation because I couldn't find one that was in the price range and worked well. The motion detection works with the camera itself by calculating the difference of two adjacent frames. I still use the arduino for the illumination because I have already bought it, but you could use the gpio pins of the raspi instead for controlling the LEDs.
For the optimal setup you need the following things:
- Raspberry Pi4
- LEDs
- Raspberry Pi Camera

I installed everything in junction boxes and placed it next to the camera to make it waterproof. One thing I haven't done yet is to control the cat flap. I have a flap at home that detects the chip of the cat to make sure only our cat can enter. I planned to hijack the electronics of that flap and place an and gate in there. I don't know if it will work exactly as I imagine it, so there is still some room for experimentation.

**Comment by sandmen** [comment]
Ok, I have the Hardware installed, 
Image flashed, and python stuff installed.
Some files adjusted for the path...

After starting he is asking for the resnet_3.pth model....
Have a nice weekend.

**Comment by julianZeitler** [comment]
Glad it worked so far. I have some trouble pushing certain changes to the repo because the model files are too big. I will try to push the other changes later, so you can run it. If you want to get it to run now, you can try to download the released I published in April, which classifies between cat and no cat. In the file split_check.py you have to change the paths to match your system. The recorded videos will be saved in these folders

**Comment by julianZeitler** [comment]
You probably have to change some stuff for the lighting. I connected the Pi to an arduino via USB to control the lighting. So in the code, the Pi tries to connect with a serial port. If you attached the lights with the GPIO Ports, you will have to adjust some stuff in record.py, where the communication with the arduino happens. Instead of sending serial signals you should be able to control the lights directly

**Comment by julianZeitler** [comment]
The project is still in an early stage of development so not everything is working as it should

**Comment by sandmen** [comment]
> You probably have to change some stuff for the lighting. I connected the Pi to an arduino via USB to control the lighting. So in the code, the Pi tries to connect with a serial port. If you attached the lights with the GPIO Ports, you will have to adjust some stuff in record.py, where the communication with the arduino happens. Instead of sending serial signals you should be able to control the lights directly

I have already seen this arduino stuff. Some LED's are already installed. 
I think, I have to improve here later. Difficult to say how it performs without the video results.

**Comment by julianZeitler** [comment]
For testing you can simply write a small program to record videos with the Picamera2 library https://github.com/raspberrypi/picamera2/tree/main/examples
You can try the capture_video.py from the link

**Comment by julianZeitler** [comment]
I wrote the instructions for the project and fixed the resnet_3.pth error. I will close this issue, if you have additional questions, feel free to open a new issue. 
Kind regards
